# Generated by Django 3.2.7 on 2021-10-05 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0003_alter_userfavoritesong_favourite_song'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavoritesong',
            unique_together={('user', 'favourite_song')},
        ),
    ]
