# Generated by Django 3.2.7 on 2021-10-05 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0004_alter_userfavoritesong_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritesong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
