# Generated by Django 3.2.7 on 2021-10-05 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0005_alter_userfavoritesong_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritesong',
            name='favourite_songs',
            field=models.ManyToManyField(to='music_app.Song'),
        ),
        migrations.AlterField(
            model_name='userfavoritesong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritesong',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfavoritesong',
            name='favourite_song',
        ),
    ]
